on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze project source
        run: dart analyze
  web:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter build web --build-number=${{github.run_number}} --base-href "/track_map/"
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: build/web/**
      - name: Archive GitHub Page
        if: github.ref == 'refs/heads/main'
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web/

  android:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: flutter build apk --build-number=${{github.run_number}}
      - run: flutter build appbundle --build-number=${{github.run_number}}
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android
          path: |
            build/app/outputs/bundle/release/app-release.aab
            build/app/outputs/flutter-apk/app-release.apk*
  ios:
    needs: lint
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter build ipa --no-codesign --build-number=${{github.run_number}}
      - name: Export unsigned IPA
        run: |
          ARCHIVE_PATH=$PWD/build/ios/archive/Runner.xcarchive
          OUTPUT_DIR=$PWD/build/ios/archive
          APP_NAME="Runner"
          TMP_DIR=$(mktemp -d)
          mkdir -p "$TMP_DIR/Payload"
          cp -R "$ARCHIVE_PATH/Products/Applications/$APP_NAME.app" "$TMP_DIR/Payload"
          cd "$TMP_DIR"
          zip -r "$OUTPUT_DIR/$APP_NAME.ipa" Payload
          rm -rf "$TMP_DIR"
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios
          path: build/ios/archive/Runner.ipa

  # Deployment
  # Deploy page on every main
  deploy_web:
    if: github.ref == 'refs/heads/main'
    needs: web
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [ android, ios, web ]
    permissions:
      contents: write
    steps:
    - uses: actions/download-artifact@v4
      with:
        path: artifacts/
    - uses: actions/checkout@v4
    - name: Setup Flutter SDK
      uses: subosito/flutter-action@v2
      with:
        channel: stable
    - name: Create GitHub Release
      id: release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/Runner.ipa
          artifacts/app-release.aab
          artifacts/app-release.apk
    - name: Update AltStore source
      with:
        DOWNLOAD_PATH: "${{ fromJSON(steps.release.outputs.assets)[0].browser_download_url }}"
      run: dart run altstore_updater update -s altstore.json --ipa artifacts/Runner.ipa --url=${DOWNLOAD_PATH}
    - uses: stefanzweifel/git-auto-commit-action@v6
      with:
        branch: main
        commit_message: "[skip ci] Update AltStore source"
        file_pattern: "altstore.json"